# Generated by Django 3.1.4 on 2021-01-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_remove_tweet_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
